[package]
name = "rust_proptest"
version = "0.1.0"
authors = ["Matthew Vernacchia <mvernacc@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
proptest = "1.0.0"
